// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/pkg/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtimev1alpha1 "github.com/crossplane/crossplane-runtime/apis/core/v1alpha1"
	"github.com/crossplane/crossplane-runtime/pkg/event"
	"github.com/crossplane/crossplane-runtime/pkg/logging"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	cpresource "github.com/crossplane/crossplane-runtime/pkg/resource"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	svcsdkapi "github.com/aws/aws-sdk-go/service/ecr/ecriface"
	svcapi "github.com/aws/aws-sdk-go/service/ecr"
	"github.com/aws/aws-sdk-go/aws/session"
	ackerr "github.com/aws/aws-controllers-k8s/pkg/errors"

	"github.com/muvaf/test-generated-aws/apis/ecr/v1alpha1"
	awsclient "github.com/muvaf/test-generated-aws/pkg/client"
)

const (
	errUnexpectedObject = "managed resource is not an repository resource"

	errCreateSession = "cannot create a new session"
	errCreate = "cannot create Repository in AWS"
)

// SetupRepository adds a controller that reconciles Repository.
func SetupRepository(mgr ctrl.Manager, l logging.Logger) error {
	name := managed.ControllerName(v1alpha1.RepositoryGroupKind)
	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		For(&v1alpha1.Repository{}).
		Complete(managed.NewReconciler(mgr,
			cpresource.ManagedKind(v1alpha1.RepositoryGroupVersionKind),
			managed.WithExternalConnecter(&connector{kube: mgr.GetClient()}),
			managed.WithReferenceResolver(managed.NewAPISimpleReferenceResolver(mgr.GetClient())),
			managed.WithConnectionPublishers(),
			managed.WithLogger(l.WithValues("controller", name)),
			managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name)))))
}

type connector struct {
	kube client.Client
}

func (c *connector) Connect(ctx context.Context, mg cpresource.Managed) (managed.ExternalClient, error) {
	cr, ok := mg.(*v1alpha1.Repository)
	if !ok {
		return nil, errors.New(errUnexpectedObject)
	}
	cfg, err := awsclient.GetConfig(ctx, c.kube, mg, cr.Spec.ForProvider.Region)
	if err != nil {
		return nil, err
	}
	sess, err := session.NewSession(cfg)
  return &external{client: svcapi.New(sess), kube: c.kube}, errors.Wrap(err, errCreateSession)
}

type external struct {
	kube   client.Client
	client svcsdkapi.ECRAPI
}

func (e *external) Observe(ctx context.Context, mg cpresource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.Repository)
	if !ok {
		return managed.ExternalObservation{}, errors.New(errUnexpectedObject)
	}

	cr.SetConditions(runtimev1alpha1.Available())
	input := GenerateDescribeRepositoriesInput(cr)
	// TODO(muvaf): Generated conversion code has logic about the input, like if(len...)
	// and has a return statement we can't control here in an arbitrary function.
	// TODO(muvaf): Generated code has an assumption about the module name of the type (svcapitypes)
	// but that doesn't always hold true.

	resp, err := e.client.DescribeRepositoriesWithContext(ctx, input)
	if err != nil {
		if awsErr, ok := ackerr.AWSError(err); ok && awsErr.Code() == "UNKNOWN" {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, err
	}

	if len(resp.Repositories) == 0 {
		return nil, ackerr.NotFound
	}
	found := false
	for _, elem := range resp.Repositories {
		if elem.CreatedAt != nil {
			cr.Status.AtProvider.CreatedAt = &metav1.Time{*elem.CreatedAt}
		}
		if elem.EncryptionConfiguration != nil {
			f1 := &svcapitypes.EncryptionConfiguration{}
			if elem.EncryptionConfiguration.EncryptionType != nil {
				f1.EncryptionType = elem.EncryptionConfiguration.EncryptionType
			}
			if elem.EncryptionConfiguration.KmsKey != nil {
				f1.KMSKey = elem.EncryptionConfiguration.KmsKey
			}
			cr.Spec.ForProvider.EncryptionConfiguration = f1
		}
		if elem.ImageScanningConfiguration != nil {
			f2 := &svcapitypes.ImageScanningConfiguration{}
			if elem.ImageScanningConfiguration.ScanOnPush != nil {
				f2.ScanOnPush = elem.ImageScanningConfiguration.ScanOnPush
			}
			cr.Spec.ForProvider.ImageScanningConfiguration = f2
		}
		if elem.ImageTagMutability != nil {
			cr.Spec.ForProvider.ImageTagMutability = elem.ImageTagMutability
		}
		if elem.RegistryId != nil {
			cr.Status.AtProvider.RegistryID = elem.RegistryId
		}
		if elem.RepositoryArn != nil {
			if cr.Status.ACKResourceMetadata == nil {
				cr.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.RepositoryArn)
			cr.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.RepositoryName != nil {
			cr.Spec.ForProvider.RepositoryName = elem.RepositoryName
		}
		if elem.RepositoryUri != nil {
			cr.Status.AtProvider.RepositoryURI = elem.RepositoryUri
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}


	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: true,
	}, nil
}

func (e *external) Create(ctx context.Context, mg cpresource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.Repository)
	if !ok {
		return managed.ExternalCreation{}, errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(runtimev1alpha1.Creating())
	input := GenerateCreateRepositoryInput(cr)
  
  	resp, err := e.client.CreateRepositoryWithContext(ctx, input)
  	if err != nil {
  	  return managed.ExternalCreation{}, errors.Wrap(err, errCreate)
  	}
  
	if resp.Repository.CreatedAt != nil {
		cr.Status.AtProvider.CreatedAt = &metav1.Time{*resp.Repository.CreatedAt}
	}
	if resp.Repository.RegistryId != nil {
		cr.Status.AtProvider.RegistryID = resp.Repository.RegistryId
	}
	if resp.Repository.RepositoryUri != nil {
		cr.Status.AtProvider.RepositoryURI = resp.Repository.RepositoryUri
	}

	return managed.ExternalCreation{}, nil
}

func (e *external) Update(ctx context.Context, mg cpresource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*v1alpha1.Repository)
	if !ok {
		return managed.ExternalUpdate{}, errors.New(errUnexpectedObject)
	}
	cr.SetConditions(runtimev1alpha1.Available())
	return managed.ExternalUpdate{}, nil
}

func (e *external) Delete(ctx context.Context, mg cpresource.Managed) error {
	cr, ok := mg.(*v1alpha1.Repository)
	if !ok {
		return errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(runtimev1alpha1.Deleting())
  	input := GenerateDeleteRepositoryInput(cr)
  	_, err := e.client.DeleteRepositoryWithContext(ctx, input)
  	// TODO(muvaf): Ignore NotFound errors here.
  	return errors.Wrap(err, errCreate)
}
