// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	runtimev1alpha1 "github.com/crossplane/crossplane-runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// BackupParameters defines the desired state of Backup
type BackupParameters struct {
	BackupName *string `json:"backupName,omitempty"`
	TableName *string `json:"tableName,omitempty"`
}

// BackupSpec defines the desired state of Backup
type BackupSpec struct {
	runtimev1alpha1.ResourceSpec `json:",inline"`
	ForProvider BackupParameters `json:"forProvider"`
}

// BackupObservation defines the observed state of Backup
type BackupObservation struct {
	BackupCreationDateTime *metav1.Time `json:"backupCreationDateTime,omitempty"`
	BackupExpiryDateTime *metav1.Time `json:"backupExpiryDateTime,omitempty"`
	BackupSizeBytes *int64 `json:"backupSizeBytes,omitempty"`
	BackupStatus *string `json:"backupStatus,omitempty"`
	BackupType *string `json:"backupType,omitempty"`
}

// BackupStatus defines the observed state of Backup.
type BackupStatus struct {
	runtimev1alpha1.ResourceStatus `json:",inline"`
	AtProvider BackupObservation `json:"atProvider"`
}


// +kubebuilder:object:root=true

// Backup is the Schema for the Backups API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type Backup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec   BackupSpec   `json:"spec,omitempty"`
	Status BackupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BackupList contains a list of Backups
type BackupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items []Backup `json:"items"`
}

// Repository type metadata.
var (
	BackupKind             = "Backup"
	BackupGroupKind        = schema.GroupKind{Group: Group, Kind: BackupKind}.String()
	BackupKindAPIVersion   = BackupKind + "." + GroupVersion.String()
	BackupGroupVersionKind = GroupVersion.WithKind(BackupKind)
)

func init() {
	SchemeBuilder.Register(&Backup{}, &BackupList{})
}

